### ISSUE TITLE
ファイルを選択したら、クソコラを作成ボタンを有効にする。あと、選択した感を出す

### ISSUE THREAD

**Issue by daisuke85a** [gokigen-ch/kusocolla-maker-1#20]

**Comment by daisuke85a** [comment]
ここを参考にすれば出来そう。JSでやる。

https://developer.mozilla.org/ja/docs/Web/HTML/Element/Input/file

**Comment by daisuke85a** [comment]
画像のプレビュー入れてみたんだけどうざいかな・・・
![プレビューいる？ mov](https://user-images.githubusercontent.com/34975744/72134187-b3204880-33c6-11ea-90eb-e401cde27d07.gif)

**Comment by daisuke85a** [comment]
@eri-yamada103 
画像のプレビューについて、ご意見いただけたら幸いでござる。

**Comment by eri-yamada103** [comment]
あった方が良いと思いました！！！！
（画像がおもしろくてずるいw）

**Comment by daisuke85a** [comment]
@eri-yamada103 
サンキュー！
マージしちゃうね！
